version: '3'
 
services:
  
  flask:
    build: ./flask
    container_name: flask
    ports:
      - "5000:5000"
    networks:
      - scrapy_mysql_net
    command: ["python", "app.py"]

  scraper:
    build: ./scraper
    container_name: scraper
    networks:
      - scrapy_mysql_net
    command: ["wait-for-it", "db:3306", "--timeout=130", "--", "scrapy", "crawl", "fvs"]
 
  db:
    image: mysql
    container_name: db
    command: ["--init-file=/tmp/mysql-init.sql", "--default-authentication-plugin=caching_sha2_password"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db/db_dir:/var/lib/mysql
      - ./db/mysql-init.sql:/tmp/mysql-init.sql
    networks:
      - scrapy_mysql_net
    ports:
      - "3307:3306"
    expose:
      - 3306
 
volumes:
  db_dir:
 
networks:
  scrapy_mysql_net: